version: '3.8'

services:
  postgres-aoj:
    restart: always
    image: postgres:latest
    container_name: postgres-aoj
    environment:
      POSTGRES_PASSWORD: qwerty
      POSTGRES_USER: postgres 
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    # volumes:
    #   - ./.database/postgres/data:/var/lib/postgresql/data
    #env_file:
    #  - .env
    ports:
      - 5432:5432

  aoj-srv:
    image: aoj-srv
    container_name: aoj-srv
    build: .
    ports:
      - "0.0.0.0:8088:8088"
    depends_on:
      postgres-aoj:
        condition: service_healthy
    volumes:
      - /home/tyazhik/aoj-logs:/logs/
    #env_file:
    #  - .env
